using System;
using System.ComponentModel.DataAnnotations;
#nullable enable

namespace ApiDataStreamToSqlDb.Models
{
    public class OpenDataPortalPropertyModel
    {
        [Required]
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public string? AccountId { get; set; }
        public string? JurisdictionCode { get; set; }
        public string? CountyName { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string? CountyCode { get; set; }
        public string? DistrictWard { get; set; }
        public string? AccountNumber { get; set; }
        public string? GeographicCode { get; set; }
        public string? OwnerOccupancyCode { get; set; }
        public string? Owner1FullName { get; set; }
        public string? NameKey { get; set; }
        public string? OwnerStreet { get; set; }
        public string? OwnerCity { get; set; }
        public string? OwnerState { get; set; }
        public string? OwnerZipCode { get; set; }
        public string? OwnerZipCodeExtension { get; set; }
        public string? LegalDescriptionLine1 { get; set; }
        public string? LegalDescriptionLine2 { get; set; }
        public string? LegalDescriptionLine3 { get; set; }
        public string? ViewEditionYear { get; set; }
        public string? MDPStreet { get; set; }
        public string? MDPCity { get; set; }
        public string? MDPZipCode { get; set; }
        public string? PremiseAddressNumber { get; set; }
        public string? PremiseAddressDirection { get; set; }
        public string? PremiseAddressName { get; set; }
        public string? PremiseAddressType { get; set; }
        public string? PremiseAddressCity { get; set; }
        public string? PremiseAddressZipCode { get; set; }
        public string? PremiseAddressZipCodeExtension { get; set; }
        public string? DeedReference1ClerkInitials { get; set; }
        public string? DeedReference1Liber { get; set; }
        public string? DeedReference1Folio { get; set; }
        public string? TownCode { get; set; }
        public string? SubdivisionCode { get; set; }
        public string? Lot { get; set; }
        public string? Map { get; set; }
        public string? Grid { get; set; }
        public string? Parcel { get; set; }
        public string? ZoningCode { get; set; }
        public string? ExemptClass { get; set; }
        public string? MDPStreetAddressTypeCode { get; set; }
        public string? LandUseCode { get; set; }
        public string? MultiParentAccount { get; set; }
        public string? TaxClass { get; set; }
        public string? RecreationalInfluence { get; set; }
        public string? BureauOfPublicRoadsUseCode { get; set; }
        public string? AdValoremCode { get; set; }
        public string? PropertyFactorsUtilitiesWater { get; set; }
        public string? PropertyFactorsUtilitiesSewer { get; set; }
        public string? PropertyFactorsLocationWaterfront { get; set; }
        public string? PropertyFactorsStreetPaved { get; set; }
        public string? PropertyFactorsStreetUnpaved { get; set; }
        public string? PropertyFactorsInfluenceCommercialIndustrial { get; set; }
        public string? PropertyFactorsInfluenceHistorical { get; set; }
        public string? FieldCardNumberPrimary { get; set; }
        public string? FieldCardNumberSecondary { get; set; }
        public string? FieldCardNumberSubset3 { get; set; }
        public string? FieldCardNumberSubset4 { get; set; }
        public string? SalesSegment1TransferNumber { get; set; }
        public string? SalesSegment1GrantorFullName { get; set; }
        public string? SalesSegment1GrantorDeedReferenceLiber { get; set; }
        public string? SalesSegment1GrantorDeedReferenceFolio { get; set; }
        public string? SalesSegment1HowConveyed { get; set; }
        public DateOnly? SalesSegment1TransferDate { get; set; }
        public int SalesSegment1Consideration { get; set; }
        public int SalesSegment1Mortgage { get; set; }
        public int SalesSegment1MarketLandValue { get; set; }
        public int SalesSegment1MarketImprovementValue { get; set; }
        public string? SalesSegment2TransferNumber { get; set; }
        public string? SalesSegment2GrantorDeedReferenceLiber { get; set; }
        public string? SalesSegment2GrantorDeedReferenceFolio { get; set; }
        public string? SalesSegment2HowConveyed { get; set; }
        public DateOnly? SalesSegment2TransferDate { get; set; }
        public int SalesSegment2Consideration { get; set; }
        public int SalesSegment2Mortgage { get; set; }
        public int SalesSegment2MarketLandValue { get; set; }
        public int SalesSegment2MarketImprovementValue { get; set; }
        public string? SalesSegment3TransferNumber { get; set; }
        public string? SalesSegment3GrantorDeedReferenceLiber { get; set; }
        public string? SalesSegment3GrantorDeedReferenceFolio { get; set; }
        public string? SalesSegment3HowConveyed { get; set; }
        public DateOnly? SalesSegment3TransferDate { get; set; }
        public int SalesSegment3Consideration { get; set; }
        public int SalesSegment3Mortgage { get; set; }
        public int SalesSegment3MarketLandValue { get; set; }
        public int SalesSegment3MarketImprovementValue { get; set; }
        public int FullAndPartialExemptionsCountyExemptAssessment { get; set; }
        public int FullAndPartialExemptionsCountyExemptPercentage { get; set; }
        public int FullAndPartialExemptionsStateExemptAssessment { get; set; }
        public int FullAndPartialExemptionsStateExemptPercentage { get; set; }
        public int FullAndPartialExemptionsMunicipalExemptAssessment { get; set; }
        public int FullAndPartialExemptionsMunicipalExemptPercentage { get; set; }
        public int FullAndPartialExemptionsPriorExemptCountyAssessment { get; set; }
        public int FullAndPartialExemptionsPriorExemptCountyPercentage { get; set; }
        public int FullAndPartialExemptionsPriorExemptStateAssessment { get; set; }
        public int FullAndPartialExemptionsPriorExemptStatePercentage { get; set; }
        public int FullAndPartialExemptionsPriorExemptMunicipalAssessment { get; set; }
        public int FullAndPartialExemptionsPriorExemptMunicipalPercentage { get; set; }
        public int BaseCycleDataLandValue { get; set; }
        public int BaseCycleDataImprovementsValue { get; set; }
        public int BaseCycleDataPreferentialLandValue { get; set; }
        public int BaseCycleDataCircuitBreakerValue { get; set; }
        public DateOnly? BaseCycleDataDateAssessed { get; set; }
        public DateOnly? BaseCycleDataDateInspected { get; set; }
        public int PriorAssessmentYearTotalAssessment { get; set; }
        public int PriorAssessmentYearCircuitBreakerAssessment { get; set; }
        public int CurrentCycleDataLandValue { get; set; }
        public int CurrentCycleDataImprovementsValue { get; set; }
        public int CurrentCycleDataPreferentialLandValue { get; set; }
        public int CurrentCycleDataCircuitBreakerValue { get; set; }
        public DateOnly? CurrentCycleDataDateInspected { get; set; }
        public DateOnly? CurrentCycleDataDateAssessed { get; set; }
        public int CurrentAssessmentYearTotalPhaseInValue { get; set; }
        public int CurrentAssessmentYearTotalAssessment { get; set; }
        public int CurrentAssessmentYearCircuitBreakerPhaseInValue { get; set; }
        public int CurrentAssessmentYearCircuitBreakerAssessment { get; set; }
        public int NewConstructionDataBaseLandValue { get; set; }
        public int NewConstructionDataBaseImprovementValue { get; set; }
        public int NewConstructionDataProposedLandValue { get; set; }
        public int NewConstructionDataProposedImprovementValue { get; set; }
        public string? NewConstructionDataActivityTaxYear { get; set; }
        public DateOnly? NewConstructionDataDateUpdated { get; set; }
        public int NewConstructionDataCountyAssessmentCredit { get; set; }
        public int NewConstructionDataStateAssessmentCredit { get; set; }
        public int NewConstructionDataMunicipalAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPreviousStateAssessmentCredit { get; set; }
        public int AssessmentCreditProgramCurrentStateAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPreviousCountyAssessmentCredit { get; set; }
        public int AssessmentCreditProgramCurrentCountyAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPreviousMunicipalAssessmentCredit { get; set; }
        public int AssessmentCreditProgramCurrentMunicipalAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPriorYear3StateAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPriorYear3CountyAssessmentCredit { get; set; }
        public int AssessmentCreditProgramPriorYear3MunicipalAssessmentCredit { get; set; }
        public string? SpecialDatesAndDataFCMACode { get; set; }
        public DateOnly? SpecialDatesAndDataRezonedRealityDate { get; set; }
        public DateOnly? SpecialDatesAndDataInchoateLienDate { get; set; }
        public DateOnly? SpecialDatesAndDataCountryClubAssessmentDate { get; set; }
        public DateOnly? SpecialDatesAndDataCountryClubExpirationDate { get; set; }
        public DateOnly? SpecialDatesAndDataCountryClubExtensionDate { get; set; }
        public int SpecialDatesAndDataAgriculturalLandPreservationFDNArea { get; set; }
        public DateOnly? SpecialDatesAndDataEnterpriseZoneDate { get; set; }
        public int SpecialDatesAndDataEnterpriseZoneAssessment { get; set; }
        public DateOnly? SpecialDatesAndDataPlannedDevelopmentDate { get; set; }
        public DateOnly? SpecialDatesAndDataNonPercTestDate { get; set; }
        public int SpecialDatesAndDataNonPercArea { get; set; }
        public DateOnly? SpecialDatesAndDataAgriculturalTaxLiabilityDueDate { get; set; }
        public DateOnly? SpecialDatesAndDataLetterOfIntentDate { get; set; }
        public DateOnly? SpecialDatesAndDataZoningChangeDate { get; set; }
        public DateOnly? SpecialDatesAndDataTaxCourtDate { get; set; }
        public DateOnly? SpecialDatesAndDataAppealBoardDate { get; set; }
        public string? CAMASystemDataDwellingGradeCode { get; set; }
        public string? CAMASystemDataDwellingConditionCode { get; set; }
        public string? CAMASystemDataYearBuilt { get; set; }
        public string? CAMASystemDataSetNumber { get; set; }
        public string? CAMASystemDataSubsetNumber { get; set; }
        public int CAMASystemDataNumberOfDwellingUnits { get; set; }
        public int CAMASystemDataNumberOfStories { get; set; }
        public int CAMASystemDataStructureAreaSquareFeet { get; set; }
        public int CAMASystemDataLandArea { get; set; }
        public string? CAMASystemDataLandUnitOfMeasure { get; set; }
        public int CAMASystemDataEffectiveWidth { get; set; }
        public int CAMASystemDataEffectiveDepth { get; set; }
        public string? TaxRollValuesTaxYear { get; set; }
        public int TaxRollValuesCountyAssessment { get; set; }
        public int TaxRollValuesStateAssessment { get; set; }
        public int TaxRollValuesMunicipalAssessment { get; set; }
        public int TaxRollValuesStateAssessmentCredit { get; set; }
        public int TaxRollValuesCountyAssessmentCredit { get; set; }
        public int TaxRollValuesMunicipalAssessmentCredit { get; set; }
        public int TaxRollValuesHomeownerProgramTotalCredit { get; set; }
        public int TaxRollValuesHomeownerProgramCountyLiability { get; set; }
        public int TaxRollValuesHomeownerProgramMunicipalityLiability { get; set; }
        public DateOnly? TaxRollValuesTaxRollBillingDate { get; set; }
        public DateOnly? HomesteadQualificationDate { get; set; }
        public string? AdditionalCAMADataPermitType { get; set; }
        public string? AdditionalCAMADataDwellingConstructionCode { get; set; }
        public string? AdditionalCAMADataBuildingStyleCodeAndDescription { get; set; }
        public string? AdditionalCAMADataDwellingType { get; set; }
        public string? AdditionalCAMADataLandValuationUnit { get; set; }
        public string? PlatReferenceLiber { get; set; }
        public string? PlatReferenceFolio { get; set; }
        public string? ParentAccountNumberDistrictWard { get; set; }
        public string? ParentAccountNumberAccountNumber { get; set; }
        public DateOnly? LastActivityDate { get; set; }
        public DateOnly? RecordCreationDate { get; set; }
        public string? RecordCreationYear { get; set; }
        public DateOnly? RecordDeletionDate { get; set; }
        public string? RecordDeletionYear { get; set; }
        public string? AssessmentCycleYear { get; set; }
        public string? FileRecordType { get; set; }
        public DateOnly? MostRecentOpenDataPortalRecordUpdateDate { get; set; }
    }
}
